//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcureEaseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertCategoryNumber
    {
        public System.Guid AdvertCategoryNumberID { get; set; }
        public Nullable<System.Guid> AdvertID { get; set; }
        public Nullable<System.Guid> AdvertCategoryID { get; set; }
        public Nullable<System.Guid> ProjectCategoryID { get; set; }
        public string CategoryLotCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.Guid> TenantID { get; set; }
    
        public virtual AdvertCategory AdvertCategory { get; set; }
        public virtual Adverts Adverts { get; set; }
        public virtual Catalog Catalog { get; set; }
        public virtual ProjectCategory ProjectCategory { get; set; }
        public virtual Catalog Catalog { get; set; }
    }
}
