//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcureEaseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemCode()
        {
            this.Items = new HashSet<Items>();
        }
    
        public System.Guid ItemCodeID { get; set; }
        public string ItemCode1 { get; set; }
        public string ItemName { get; set; }
        public Nullable<System.Guid> TenantID { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual ItemCodeCategory ItemCodeCategory { get; set; }
        public virtual ItemCodeCategory ItemCodeCategory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items { get; set; }
    }
}
