//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcureEaseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public System.Guid ItemID { get; set; }
        public Nullable<System.Guid> ProcurementID { get; set; }
        public Nullable<System.Guid> ApprovedItemID { get; set; }
        public Nullable<System.Guid> AdvertisedItemID { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.Guid> ItemCodeID { get; set; }
    
        public virtual AdvertisedItems AdvertisedItems { get; set; }
        public virtual ApprovedItems ApprovedItems { get; set; }
        public virtual Procurements Procurements { get; set; }
        public virtual ItemCode ItemCode { get; set; }
    }
}
