//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcureEaseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationSetting
    {
        public System.Guid OrganizationID { get; set; }
        public System.Guid TelephoneNumberID { get; set; }
        public string OrganizationNameInFull { get; set; }
        public string OrganizationNameAbbreviation { get; set; }
        public string OrganizationEmail { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string AboutOrganization { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual TelephoneNumber TelephoneNumber { get; set; }
    }
}
