//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcureEaseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestForDemo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestForDemo()
        {
            this.Catalog = new HashSet<Catalog>();
        }
    
        public System.Guid RequestID { get; set; }
        public string OrganizationFullName { get; set; }
        public string OrganizationShortName { get; set; }
        public string AdministratorEmail { get; set; }
        public string AdministratorFirstName { get; set; }
        public string AdministratorLastName { get; set; }
        public string AdministratorPhoneNumber { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.Guid> TenantID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog> Catalog { get; set; }
        public virtual Catalog Catalog1 { get; set; }
    }
}
